update contracts
tonlabs/ton-client-node-js pull request #36
Opened 2020-09-11 14:04 UTC by joydark

2020-09-11 14:58 UTC, g9d approved these changes

2020-09-16 09:29 UTC, g9d requested changes
And you need to compile contract into git

2020-09-16 11:51 UTC, g9d approved these changes

2020-09-16 12:10 UTC, g9d commented
recompile tests OK: https://builder.tonlabs.io/jenkins/job/Integration/job/integration-tests/job/master/3486/

2020-09-16 12:20 UTC, melsomino approved these changes

2020-09-16 12:38 UTC, merged